---
title: "The Power of Data Simulation Part II"
subtitle: "Practical Uses of NumPy Random Generator for AB Testing"
author: "Russ Zaliznyak <[rzaliznyak@gmail.com](mailto:rzaliznyak@gmail.com)>"
date: "2025-01-20"
execute:
  echo: false
format: 
  html: 
    css: style.css
    toc: true
    toc-expand: true
    toc-indent: 1em
jupyter: python3
---


# Expand Your Toolkit

The goal of this paper is to continue to build on our last paper, [The Power of Data Simulation](https://rzaliznyak-math.github.io/random/){target="_blank"}.

By the end of this paper you will be able to simulate distributions and understand p-values, crucial concepts in AB Testing.
You'll learn how to generate millions of time-series simulations for A/B tests in just seconds. You'll discover how to visualize statistical power, enhancing your intuition for sample sizes and effect size magnitudes.

You'll have a deeper toolkit for conducting AB tests using NumPy's powerful random functions, enabling more insightful statistical modeling in your work.

# Traditional Signifigance Test

When we kick off a traditional A/B *significance test*, we make a big assumption that our two test conditions perform equally.

1. We gather evidence by accumulating samples and then calculate a *p-value*. This value estimates the probability of seeing our results (or more extreme), given equality between our two test conditions.

2. If the p-value is low enough, we are forced to conclude that are our test conditions are not equal. (*Statistically Significant*)

In order to perform this analysis, we need to build a *Null Distribution* --- this distribution reveals what results we SHOULD expect to see assuming there is no difference between test conditions.

# Null Distributions

CODE HERE